stages:
  - build
  - deploy

build:
  stage: build
  script:
    - export PATH=/home/gitlab-runner/.nvm/versions/node/v20.14.0/bin/:$PATH

include:
  - local: .gitlab/prod.yml
  - local: .gitlab/dev.yml
  - local: .gitlab/test.yml

