version: "3.8"

services:
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
        depends_on:
            - prometheus
            - loki
        volumes:
            - grafana-data:/var/lib/grafana

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

    loki:
        image: grafana/loki:latest
        container_name: loki
        ports:
            - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
            - ./loki-config.yaml:/etc/loki/local-config.yaml

    promtail:
        image: grafana/promtail:latest
        container_name: promtail
        volumes:
            - ./promtail-config.yaml:/etc/promtail/config.yml
            - /var/log:/var/log
        command: -config.file=/etc/promtail/config.yml

volumes:
    grafana-data:
