global:
    scrape_interval: 15s

scrape_configs:
    - job_name: "nestjs"
      static_configs:
          - targets: ["host.docker.internal:3001"]
    - job_name: "loki"
      static_configs:
          - targets: ["loki:3100"]
