build-dev:
  stage: build
  before_script:
    - git pull origin dev
  script:
    - npm run build:prod
  only:
    - dev
  tags:
    - main-runner

deploy-dev:
  stage: deploy
  before_script:
    - pm2 status
  script:
    - pm2 restart "brusnika-back-dev"
  only:
    - dev
  tags:
    - main-runner
