build-prod:
  stage: build
  before_script:
    - export PATH=/home/gitlab-runner/.nvm/versions/node/v20.14.0/bin/:$PATH
    - git pull origin prod
  script:
    - npm run build:prod
  only:
    - prod
  tags:
    - main-runner

deploy-prod:
  stage: deploy
  before_script:
    - pm2 status
  script:
    - pm2 restart "brusnika-back"
  only:
    - prod
  tags:
    - main-runner
