import { QueryBuilder } from "typeorm";

import { WithOutToDto } from "types";

import { BuildingsEntity } from "../../modules/buildings/buildings.entity";
import {
	CommercialStatus,
	PremisesEntity,
	PremisesType,
	PuchaseOptions,
} from "../../modules/premises/premises.entity";

function findBuildingId(buildings: BuildingsEntity[], name: string) {
	return buildings.find((e) => e.name === name)?.id ?? "";
}

export async function up(query: QueryBuilder<object>) {
	const buildings = await query
		.select(["c.id AS id", "c.name AS name"])
		.from(BuildingsEntity, "c")
		.getRawMany<BuildingsEntity>();

	const premises: WithOutToDto<
		Omit<
			PremisesEntity,
			"id" | "section" | "building" | "createdAt" | "updatedAt"
		>
	>[] = [
		{
			building_id: findBuildingId(buildings, "Дом 1"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
		{
			building_id: findBuildingId(buildings, "Дом 2"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
		{
			building_id: findBuildingId(buildings, "Дом 3"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},

		{
			building_id: findBuildingId(buildings, "Дом 1"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
		{
			building_id: findBuildingId(buildings, "Дом 2"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
		{
			building_id: findBuildingId(buildings, "Дом 3"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},

		{
			building_id: findBuildingId(buildings, "Дом 1"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
		{
			building_id: findBuildingId(buildings, "Дом 2"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
		{
			building_id: findBuildingId(buildings, "Дом 3"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},

		{
			building_id: findBuildingId(buildings, "Дом 1"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
		{
			building_id: findBuildingId(buildings, "Дом 2"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
		{
			building_id: findBuildingId(buildings, "Дом 3"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},

		{
			building_id: findBuildingId(buildings, "Дом 1"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
		{
			building_id: findBuildingId(buildings, "Дом 2"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
		{
			building_id: findBuildingId(buildings, "Дом 3"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},

		{
			building_id: findBuildingId(buildings, "Дом 1"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
		{
			building_id: findBuildingId(buildings, "Дом 2"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
		{
			building_id: findBuildingId(buildings, "Дом 3"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},

		{
			building_id: findBuildingId(buildings, "Дом 1"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
		{
			building_id: findBuildingId(buildings, "Дом 2"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
		{
			building_id: findBuildingId(buildings, "Дом 3"),
			number: 1,
			name: "",
			type: PremisesType.APARTMENT,
			price: 20_000,
			size: 30,
			status: CommercialStatus.FREE,
			purchaseOption: PuchaseOptions.MORTAGE,
			floor: 1,
			photo: "premise_apartment_default_image.jpg",
			rooms: 5,
			photos: [
				"premise_apartment_default_image.jpg",
				"premise_apartment_default_image.jpg",
			],
			similiarApartmentCount: 0,
			title: "",
			end_date: new Date(),
			mortagePayment: 100,
			is_sold: false,
		},
	];

	await query.insert().into(PremisesEntity).values(premises).execute();
}

export async function down(query: QueryBuilder<object>) {
	await query.delete().from(PremisesEntity).execute();
}
