import { CustomPrompt } from "./prompt";

export type IPostgresPrompt = CustomPrompt<number, "postgres">;

export const PostgresPrompts: IPostgresPrompt[] = [
	{
		promptId: 1,
		promptType: "postgres",
		promptCode: "20000",
		promptCondition: "case_not_found",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 2,
		promptType: "postgres",
		promptCode: "21000",
		promptCondition: "cardinality_violation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 3,
		promptType: "postgres",
		promptCode: "22000",
		promptCondition: "data_exception",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 4,
		promptType: "postgres",
		promptCode: "22001",
		promptCondition: "string_data_right_truncation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 5,
		promptType: "postgres",
		promptCode: "22002",
		promptCondition: "null_value_no_indicator_parameter",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 6,
		promptType: "postgres",
		promptCode: "22003",
		promptCondition: "numeric_value_out_of_range",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 7,
		promptType: "postgres",
		promptCode: "22004",
		promptCondition: "null_value_not_allowed",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 8,
		promptType: "postgres",
		promptCode: "22005",
		promptCondition: "error_in_assignment",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 9,
		promptType: "postgres",
		promptCode: "22007",
		promptCondition: "invalid_datetime_format",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 10,
		promptType: "postgres",
		promptCode: "22008",
		promptCondition: "datetime_field_overflow",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 11,
		promptType: "postgres",
		promptCode: "22009",
		promptCondition: "invalid_time_zone_displacement_value",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 12,
		promptType: "postgres",
		promptCode: "22010",
		promptCondition: "invalid_indicator_parameter_value",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 13,
		promptType: "postgres",
		promptCode: "22011",
		promptCondition: "substring_error",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 14,
		promptType: "postgres",
		promptCode: "22012",
		promptCondition: "division_by_zero",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 15,
		promptType: "postgres",
		promptCode: "22013",
		promptCondition: "invalid_preceding_or_following_size",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 16,
		promptType: "postgres",
		promptCode: "22014",
		promptCondition: "invalid_argument_for_ntile_function",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 17,
		promptType: "postgres",
		promptCode: "22015",
		promptCondition: "interval_field_overflow",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 18,
		promptType: "postgres",
		promptCode: "22016",
		promptCondition: "invalid_argument_for_nth_value_function",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 19,
		promptType: "postgres",
		promptCode: "22018",
		promptCondition: "invalid_character_value_for_cast",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 20,
		promptType: "postgres",
		promptCode: "22019",
		promptCondition: "invalid_escape_character",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 21,
		promptType: "postgres",
		promptCode: "22021",
		promptCondition: "character_not_in_repertoire",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 22,
		promptType: "postgres",
		promptCode: "22022",
		promptCondition: "indicator_overflow",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 23,
		promptType: "postgres",
		promptCode: "22023",
		promptCondition: "invalid_parameter_value",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 24,
		promptType: "postgres",
		promptCode: "22024",
		promptCondition: "unterminated_c_string",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 25,
		promptType: "postgres",
		promptCode: "22025",
		promptCondition: "invalid_escape_sequence",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 26,
		promptType: "postgres",
		promptCode: "22026",
		promptCondition: "string_data_length_mismatch",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 27,
		promptType: "postgres",
		promptCode: "22027",
		promptCondition: "trim_error",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 28,
		promptType: "postgres",
		promptCode: "22030",
		promptCondition: "duplicate_json_object_key_value",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 29,
		promptType: "postgres",
		promptCode: "22031",
		promptCondition: "invalid_argument_for_sql_json_datetime_function",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 30,
		promptType: "postgres",
		promptCode: "22032",
		promptCondition: "invalid_json_text",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 31,
		promptType: "postgres",
		promptCode: "22033",
		promptCondition: "invalid_sql_json_subscript",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 32,
		promptType: "postgres",
		promptCode: "22034",
		promptCondition: "more_than_one_sql_json_item",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 33,
		promptType: "postgres",
		promptCode: "22035",
		promptCondition: "no_sql_json_item",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 34,
		promptType: "postgres",
		promptCode: "22036",
		promptCondition: "non_numeric_sql_json_item",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 35,
		promptType: "postgres",
		promptCode: "22037",
		promptCondition: "non_unique_keys_in_a_json_object",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 36,
		promptType: "postgres",
		promptCode: "22038",
		promptCondition: "singleton_sql_json_item_required",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 37,
		promptType: "postgres",
		promptCode: "22039",
		promptCondition: "sql_json_array_not_found",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 38,
		promptType: "postgres",
		promptCode: "23000",
		promptCondition: "integrity_constraint_violation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 39,
		promptType: "postgres",
		promptCode: "23001",
		promptCondition: "restrict_violation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 40,
		promptType: "postgres",
		promptCode: "23502",
		promptCondition: "not_null_violation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 41,
		promptType: "postgres",
		promptCode: "23503",
		promptCondition: "foreign_key_violation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 42,
		promptType: "postgres",
		promptCode: "23505",
		promptCondition: "unique_violation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 43,
		promptType: "postgres",
		promptCode: "23514",
		promptCondition: "check_violation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 44,
		promptType: "postgres",
		promptCode: "24000",
		promptCondition: "invalid_cursor_state",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 45,
		promptType: "postgres",
		promptCode: "25000",
		promptCondition: "invalid_transaction_state",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 46,
		promptType: "postgres",
		promptCode: "25001",
		promptCondition: "active_sql_transaction",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 47,
		promptType: "postgres",
		promptCode: "25002",
		promptCondition: "branch_transaction_already_active",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 48,
		promptType: "postgres",
		promptCode: "25003",
		promptCondition: "inappropriate_access_mode_for_branch_transaction",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 49,
		promptType: "postgres",
		promptCode: "25004",
		promptCondition: "inappropriate_isolation_level_for_branch_transaction",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 50,
		promptType: "postgres",
		promptCode: "25005",
		promptCondition: "no_active_sql_transaction_for_branch_transaction",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 51,
		promptType: "postgres",
		promptCode: "25006",
		promptCondition: "read_only_sql_transaction",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 52,
		promptType: "postgres",
		promptCode: "25007",
		promptCondition: "schema_and_data_statement_mixing_not_supported",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 53,
		promptType: "postgres",
		promptCode: "25008",
		promptCondition: "held_cursor_requires_same_isolation_level",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 54,
		promptType: "postgres",
		promptCode: "26000",
		promptCondition: "invalid_sql_statement_name",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 55,
		promptType: "postgres",
		promptCode: "27000",
		promptCondition: "triggered_data_change_violation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 56,
		promptType: "postgres",
		promptCode: "28000",
		promptCondition: "invalid_authorization_specification",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 57,
		promptType: "postgres",
		promptCode: "34000",
		promptCondition: "invalid_cursor_name",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 58,
		promptType: "postgres",
		promptCode: "38000",
		promptCondition: "external_routine_exception",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 59,
		promptType: "postgres",
		promptCode: "38001",
		promptCondition: "containing_sql_not_permitted",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 60,
		promptType: "postgres",
		promptCode: "38002",
		promptCondition: "modifying_sql_data_not_permitted",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 61,
		promptType: "postgres",
		promptCode: "38003",
		promptCondition: "prohibited_sql_statement_attempted",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 62,
		promptType: "postgres",
		promptCode: "38004",
		promptCondition: "reading_sql_data_not_permitted",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 63,
		promptType: "postgres",
		promptCode: "39000",
		promptCondition: "external_routine_invocation_exception",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 64,
		promptType: "postgres",
		promptCode: "39001",
		promptCondition: "invalid_sqlstate_returned",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 65,
		promptType: "postgres",
		promptCode: "39004",
		promptCondition: "null_value_not_allowed",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 66,
		promptType: "postgres",
		promptCode: "40000",
		promptCondition: "transaction_rollback",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 67,
		promptType: "postgres",
		promptCode: "40001",
		promptCondition: "serialization_failure",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 68,
		promptType: "postgres",
		promptCode: "40002",
		promptCondition: "transaction_integrity_constraint_violation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 69,
		promptType: "postgres",
		promptCode: "40003",
		promptCondition: "statement_completion_unknown",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 70,
		promptType: "postgres",
		promptCode: "42000",
		promptCondition: "syntax_error_or_access_rule_violation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 71,
		promptType: "postgres",
		promptCode: "42501",
		promptCondition: "insufficient_privilege",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 72,
		promptType: "postgres",
		promptCode: "42601",
		promptCondition: "syntax_error",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 73,
		promptType: "postgres",
		promptCode: "42602",
		promptCondition: "invalid_name",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 74,
		promptType: "postgres",
		promptCode: "42611",
		promptCondition: "invalid_column_definition",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 75,
		promptType: "postgres",
		promptCode: "42622",
		promptCondition: "name_too_long",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 76,
		promptType: "postgres",
		promptCode: "42701",
		promptCondition: "duplicate_column",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 77,
		promptType: "postgres",
		promptCode: "42702",
		promptCondition: "ambiguous_column",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 78,
		promptType: "postgres",
		promptCode: "42703",
		promptCondition: "undefined_column",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 79,
		promptType: "postgres",
		promptCode: "42704",
		promptCondition: "undefined_object",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 80,
		promptType: "postgres",
		promptCode: "42710",
		promptCondition: "duplicate_object",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 81,
		promptType: "postgres",
		promptCode: "42712",
		promptCondition: "duplicate_alias",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 82,
		promptType: "postgres",
		promptCode: "42723",
		promptCondition: "duplicate_function",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 83,
		promptType: "postgres",
		promptCode: "42725",
		promptCondition: "ambiguous_function",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 84,
		promptType: "postgres",
		promptCode: "42803",
		promptCondition: "grouping_error",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 85,
		promptType: "postgres",
		promptCode: "42804",
		promptCondition: "datatype_mismatch",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 86,
		promptType: "postgres",
		promptCode: "42809",
		promptCondition: "wrong_object_type",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 87,
		promptType: "postgres",
		promptCode: "42830",
		promptCondition: "invalid_foreign_key",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 88,
		promptType: "postgres",
		promptCode: "42846",
		promptCondition: "cannot_coerce",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 89,
		promptType: "postgres",
		promptCode: "42883",
		promptCondition: "undefined_function",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 90,
		promptType: "postgres",
		promptCode: "42939",
		promptCondition: "reserved_name",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 91,
		promptType: "postgres",
		promptCode: "44000",
		promptCondition: "with_check_option_violation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 92,
		promptType: "postgres",
		promptCode: "53000",
		promptCondition: "insufficient_resources",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 93,
		promptType: "postgres",
		promptCode: "53100",
		promptCondition: "disk_full",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 94,
		promptType: "postgres",
		promptCode: "53200",
		promptCondition: "out_of_memory",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 95,
		promptType: "postgres",
		promptCode: "53300",
		promptCondition: "too_many_connections",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 96,
		promptType: "postgres",
		promptCode: "53400",
		promptCondition: "configuration_limit_exceeded",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 97,
		promptType: "postgres",
		promptCode: "54000",
		promptCondition: "program_limit_exceeded",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 98,
		promptType: "postgres",
		promptCode: "54001",
		promptCondition: "statement_too_complex",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 99,
		promptType: "postgres",
		promptCode: "54011",
		promptCondition: "too_many_columns",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 100,
		promptType: "postgres",
		promptCode: "54023",
		promptCondition: "too_many_arguments",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 101,
		promptType: "postgres",
		promptCode: "55000",
		promptCondition: "object_not_in_prerequisite_state",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 102,
		promptType: "postgres",
		promptCode: "55006",
		promptCondition: "object_in_use",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 103,
		promptType: "postgres",
		promptCode: "57000",
		promptCondition: "operator_intervention",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 104,
		promptType: "postgres",
		promptCode: "57014",
		promptCondition: "query_canceled",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 105,
		promptType: "postgres",
		promptCode: "58000",
		promptCondition: "system_error",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 106,
		promptType: "postgres",
		promptCode: "58030",
		promptCondition: "io_error",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 107,
		promptType: "postgres",
		promptCode: "72000",
		promptCondition: "snapshot_too_old",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 108,
		promptType: "postgres",
		promptCode: "00000",
		promptCondition: "successful_completion",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 109,
		promptType: "postgres",
		promptCode: "01000",
		promptCondition: "warning",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 110,
		promptType: "postgres",
		promptCode: "0100C",
		promptCondition: "dynamic_result_sets_returned",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 111,
		promptType: "postgres",
		promptCode: "01008",
		promptCondition: "implicit_zero_bit_padding",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 112,
		promptType: "postgres",
		promptCode: "01003",
		promptCondition: "null_value_eliminated_in_set_function",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 113,
		promptType: "postgres",
		promptCode: "01007",
		promptCondition: "privilege_not_granted",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 114,
		promptType: "postgres",
		promptCode: "01006",
		promptCondition: "privilege_not_revoked",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 115,
		promptType: "postgres",
		promptCode: "01004",
		promptCondition: "string_data_right_truncation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 116,
		promptType: "postgres",
		promptCode: "01P01",
		promptCondition: "deprecated_feature",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 117,
		promptType: "postgres",
		promptCode: "02000",
		promptCondition: "no_data",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 118,
		promptType: "postgres",
		promptCode: "02001",
		promptCondition: "no_additional_dynamic_result_sets_returned",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 119,
		promptType: "postgres",
		promptCode: "03000",
		promptCondition: "sql_statement_not_yet_complete",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 120,
		promptType: "postgres",
		promptCode: "08000",
		promptCondition: "connection_exception",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 121,
		promptType: "postgres",
		promptCode: "08003",
		promptCondition: "connection_does_not_exist",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 122,
		promptType: "postgres",
		promptCode: "08006",
		promptCondition: "connection_failure",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 123,
		promptType: "postgres",
		promptCode: "08001",
		promptCondition: "sqlclient_unable_to_establish_sqlconnection",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 124,
		promptType: "postgres",
		promptCode: "08004",
		promptCondition: "sqlserver_rejected_establishment_of_sqlconnection",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 125,
		promptType: "postgres",
		promptCode: "08007",
		promptCondition: "transaction_resolution_unknown",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 126,
		promptType: "postgres",
		promptCode: "08P01",
		promptCondition: "protocol_violation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 127,
		promptType: "postgres",
		promptCode: "09000",
		promptCondition: "triggered_action_exception",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 128,
		promptType: "postgres",
		promptCode: "0A000",
		promptCondition: "feature_not_supported",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 129,
		promptType: "postgres",
		promptCode: "0B000",
		promptCondition: "invalid_transaction_initiation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 130,
		promptType: "postgres",
		promptCode: "0F000",
		promptCondition: "locator_exception",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 131,
		promptType: "postgres",
		promptCode: "0F001",
		promptCondition: "invalid_locator_specification",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 132,
		promptType: "postgres",
		promptCode: "0L000",
		promptCondition: "invalid_grantor",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 133,
		promptType: "postgres",
		promptCode: "0LP01",
		promptCondition: "invalid_grant_operation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 134,
		promptType: "postgres",
		promptCode: "0P000",
		promptCondition: "invalid_role_specification",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 135,
		promptType: "postgres",
		promptCode: "0Z000",
		promptCondition: "diagnostics_exception",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 136,
		promptType: "postgres",
		promptCode: "0Z002",
		promptCondition: "stacked_diagnostics_accessed_without_active_handler",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 137,
		promptType: "postgres",
		promptCode: "2202E",
		promptCondition: "array_subscript_error",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 138,
		promptType: "postgres",
		promptCode: "2200B",
		promptCondition: "escape_character_conflict",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 139,
		promptType: "postgres",
		promptCode: "2201E",
		promptCondition: "invalid_argument_for_logarithm",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 140,
		promptType: "postgres",
		promptCode: "2201F",
		promptCondition: "invalid_argument_for_power_function",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 141,
		promptType: "postgres",
		promptCode: "2201G",
		promptCondition: "invalid_argument_for_width_bucket_function",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 142,
		promptType: "postgres",
		promptCode: "2200D",
		promptCondition: "invalid_escape_octet",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 143,
		promptType: "postgres",
		promptCode: "22P06",
		promptCondition: "nonstandard_use_of_escape_character",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 144,
		promptType: "postgres",
		promptCode: "2201B",
		promptCondition: "invalid_regular_expression",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 145,
		promptType: "postgres",
		promptCode: "2201W",
		promptCondition: "invalid_row_count_in_limit_clause",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 146,
		promptType: "postgres",
		promptCode: "2201X",
		promptCondition: "invalid_row_count_in_result_offset_clause",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 147,
		promptType: "postgres",
		promptCode: "2202H",
		promptCondition: "invalid_tablesample_argument",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 148,
		promptType: "postgres",
		promptCode: "2202G",
		promptCondition: "invalid_tablesample_repeat",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 149,
		promptType: "postgres",
		promptCode: "2200C",
		promptCondition: "invalid_use_of_escape_character",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 150,
		promptType: "postgres",
		promptCode: "2200G",
		promptCondition: "most_specific_type_mismatch",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 151,
		promptType: "postgres",
		promptCode: "2200H",
		promptCondition: "sequence_generator_limit_exceeded",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 152,
		promptType: "postgres",
		promptCode: "2200F",
		promptCondition: "zero_length_character_string",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 153,
		promptType: "postgres",
		promptCode: "22P01",
		promptCondition: "floating_point_exception",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 154,
		promptType: "postgres",
		promptCode: "22P02",
		promptCondition: "invalid_text_representation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 155,
		promptType: "postgres",
		promptCode: "22P03",
		promptCondition: "invalid_binary_representation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 156,
		promptType: "postgres",
		promptCode: "22P04",
		promptCondition: "bad_copy_file_format",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 157,
		promptType: "postgres",
		promptCode: "22P05",
		promptCondition: "untranslatable_character",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 158,
		promptType: "postgres",
		promptCode: "2200L",
		promptCondition: "not_an_xml_document",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 159,
		promptType: "postgres",
		promptCode: "2200M",
		promptCondition: "invalid_xml_document",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 160,
		promptType: "postgres",
		promptCode: "2200N",
		promptCondition: "invalid_xml_content",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 161,
		promptType: "postgres",
		promptCode: "2200S",
		promptCondition: "invalid_xml_comment",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 162,
		promptType: "postgres",
		promptCode: "2200T",
		promptCondition: "invalid_xml_processing_instruction",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 163,
		promptType: "postgres",
		promptCode: "2203A",
		promptCondition: "sql_json_member_not_found",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 164,
		promptType: "postgres",
		promptCode: "2203B",
		promptCondition: "sql_json_number_not_found",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 165,
		promptType: "postgres",
		promptCode: "2203C",
		promptCondition: "sql_json_object_not_found",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 166,
		promptType: "postgres",
		promptCode: "2203D",
		promptCondition: "too_many_json_array_elements",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 167,
		promptType: "postgres",
		promptCode: "2203E",
		promptCondition: "too_many_json_object_members",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 168,
		promptType: "postgres",
		promptCode: "2203F",
		promptCondition: "sql_json_scalar_required",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 169,
		promptType: "postgres",
		promptCode: "23P01",
		promptCondition: "exclusion_violation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 170,
		promptType: "postgres",
		promptCode: "25P01",
		promptCondition: "no_active_sql_transaction",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 171,
		promptType: "postgres",
		promptCode: "25P02",
		promptCondition: "in_failed_sql_transaction",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 172,
		promptType: "postgres",
		promptCode: "25P03",
		promptCondition: "idle_in_transaction_session_timeout",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 173,
		promptType: "postgres",
		promptCode: "28P01",
		promptCondition: "invalid_password",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 174,
		promptType: "postgres",
		promptCode: "2B000",
		promptCondition: "dependent_privilege_descriptors_still_exist",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 175,
		promptType: "postgres",
		promptCode: "2BP01",
		promptCondition: "dependent_objects_still_exist",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 176,
		promptType: "postgres",
		promptCode: "2D000",
		promptCondition: "invalid_transaction_termination",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 177,
		promptType: "postgres",
		promptCode: "2F000",
		promptCondition: "sql_routine_exception",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 178,
		promptType: "postgres",
		promptCode: "2F005",
		promptCondition: "function_executed_no_return_statement",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 179,
		promptType: "postgres",
		promptCode: "2F002",
		promptCondition: "modifying_sql_data_not_permitted",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 180,
		promptType: "postgres",
		promptCode: "2F003",
		promptCondition: "prohibited_sql_statement_attempted",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 181,
		promptType: "postgres",
		promptCode: "2F004",
		promptCondition: "reading_sql_data_not_permitted",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 182,
		promptType: "postgres",
		promptCode: "39P01",
		promptCondition: "trigger_protocol_violated",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 183,
		promptType: "postgres",
		promptCode: "39P02",
		promptCondition: "srf_protocol_violated",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 184,
		promptType: "postgres",
		promptCode: "39P03",
		promptCondition: "event_trigger_protocol_violated",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 185,
		promptType: "postgres",
		promptCode: "3B000",
		promptCondition: "savepoint_exception",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 186,
		promptType: "postgres",
		promptCode: "3B001",
		promptCondition: "invalid_savepoint_specification",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 187,
		promptType: "postgres",
		promptCode: "3D000",
		promptCondition: "invalid_catalog_name",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 188,
		promptType: "postgres",
		promptCode: "3F000",
		promptCondition: "invalid_schema_name",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 189,
		promptType: "postgres",
		promptCode: "40P01",
		promptCondition: "deadlock_detected",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 190,
		promptType: "postgres",
		promptCode: "42P20",
		promptCondition: "windowing_error",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 191,
		promptType: "postgres",
		promptCode: "42P19",
		promptCondition: "invalid_recursion",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 192,
		promptType: "postgres",
		promptCode: "42P18",
		promptCondition: "indeterminate_datatype",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 193,
		promptType: "postgres",
		promptCode: "42P21",
		promptCondition: "collation_mismatch",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 194,
		promptType: "postgres",
		promptCode: "42P22",
		promptCondition: "indeterminate_collation",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 195,
		promptType: "postgres",
		promptCode: "428C9",
		promptCondition: "generated_always",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 196,
		promptType: "postgres",
		promptCode: "42P01",
		promptCondition: "undefined_table",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 197,
		promptType: "postgres",
		promptCode: "42P02",
		promptCondition: "undefined_parameter",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 198,
		promptType: "postgres",
		promptCode: "42P03",
		promptCondition: "duplicate_cursor",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 199,
		promptType: "postgres",
		promptCode: "42P04",
		promptCondition: "duplicate_database",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 200,
		promptType: "postgres",
		promptCode: "42P05",
		promptCondition: "duplicate_prepared_statement",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 201,
		promptType: "postgres",
		promptCode: "42P06",
		promptCondition: "duplicate_schema",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 202,
		promptType: "postgres",
		promptCode: "42P07",
		promptCondition: "duplicate_table",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 203,
		promptType: "postgres",
		promptCode: "42P08",
		promptCondition: "ambiguous_parameter",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 204,
		promptType: "postgres",
		promptCode: "42P09",
		promptCondition: "ambiguous_alias",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 205,
		promptType: "postgres",
		promptCode: "42P10",
		promptCondition: "invalid_column_reference",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 206,
		promptType: "postgres",
		promptCode: "42P11",
		promptCondition: "invalid_cursor_definition",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 207,
		promptType: "postgres",
		promptCode: "42P12",
		promptCondition: "invalid_database_definition",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 208,
		promptType: "postgres",
		promptCode: "42P13",
		promptCondition: "invalid_function_definition",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 209,
		promptType: "postgres",
		promptCode: "42P14",
		promptCondition: "invalid_prepared_statement_definition",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 210,
		promptType: "postgres",
		promptCode: "42P15",
		promptCondition: "invalid_schema_definition",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 211,
		promptType: "postgres",
		promptCode: "42P16",
		promptCondition: "invalid_table_definition",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 212,
		promptType: "postgres",
		promptCode: "42P17",
		promptCondition: "invalid_object_definition",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 213,
		promptType: "postgres",
		promptCode: "55P02",
		promptCondition: "cant_change_runtime_param",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 214,
		promptType: "postgres",
		promptCode: "55P03",
		promptCondition: "lock_not_available",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 215,
		promptType: "postgres",
		promptCode: "55P04",
		promptCondition: "unsafe_new_enum_value_usage",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 216,
		promptType: "postgres",
		promptCode: "57P01",
		promptCondition: "admin_shutdown",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 217,
		promptType: "postgres",
		promptCode: "57P02",
		promptCondition: "crash_shutdown",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 218,
		promptType: "postgres",
		promptCode: "57P03",
		promptCondition: "cannot_connect_now",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 219,
		promptType: "postgres",
		promptCode: "57P04",
		promptCondition: "database_dropped",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 220,
		promptType: "postgres",
		promptCode: "58P01",
		promptCondition: "undefined_file",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 221,
		promptType: "postgres",
		promptCode: "58P02",
		promptCondition: "duplicate_file",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 222,
		promptType: "postgres",
		promptCode: "F0000",
		promptCondition: "config_file_error",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 223,
		promptType: "postgres",
		promptCode: "F0001",
		promptCondition: "lock_file_exists",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 224,
		promptType: "postgres",
		promptCode: "HV000",
		promptCondition: "fdw_error",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 225,
		promptType: "postgres",
		promptCode: "HV005",
		promptCondition: "fdw_column_name_not_found",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 226,
		promptType: "postgres",
		promptCode: "HV002",
		promptCondition: "fdw_dynamic_parameter_value_needed",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 227,
		promptType: "postgres",
		promptCode: "HV010",
		promptCondition: "fdw_function_sequence_error",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 228,
		promptType: "postgres",
		promptCode: "HV021",
		promptCondition: "fdw_inconsistent_descriptor_information",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 229,
		promptType: "postgres",
		promptCode: "HV024",
		promptCondition: "fdw_invalid_attribute_value",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 230,
		promptType: "postgres",
		promptCode: "HV007",
		promptCondition: "fdw_invalid_column_name",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 231,
		promptType: "postgres",
		promptCode: "HV008",
		promptCondition: "fdw_invalid_column_number",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 232,
		promptType: "postgres",
		promptCode: "HV004",
		promptCondition: "fdw_invalid_data_type",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 233,
		promptType: "postgres",
		promptCode: "HV006",
		promptCondition: "fdw_invalid_data_type_descriptors",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 234,
		promptType: "postgres",
		promptCode: "HV091",
		promptCondition: "fdw_invalid_descriptor_field_identifier",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 235,
		promptType: "postgres",
		promptCode: "HV00B",
		promptCondition: "fdw_invalid_handle",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 236,
		promptType: "postgres",
		promptCode: "HV00C",
		promptCondition: "fdw_invalid_option_index",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 237,
		promptType: "postgres",
		promptCode: "HV00D",
		promptCondition: "fdw_invalid_option_name",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 238,
		promptType: "postgres",
		promptCode: "HV090",
		promptCondition: "fdw_invalid_string_length_or_buffer_length",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 239,
		promptType: "postgres",
		promptCode: "HV00A",
		promptCondition: "fdw_invalid_string_format",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 240,
		promptType: "postgres",
		promptCode: "HV009",
		promptCondition: "fdw_invalid_use_of_null_pointer",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 241,
		promptType: "postgres",
		promptCode: "HV014",
		promptCondition: "fdw_too_many_handles",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 242,
		promptType: "postgres",
		promptCode: "HV001",
		promptCondition: "fdw_out_of_memory",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 243,
		promptType: "postgres",
		promptCode: "HV00P",
		promptCondition: "fdw_no_schemas",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 244,
		promptType: "postgres",
		promptCode: "HV00J",
		promptCondition: "fdw_option_name_not_found",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 245,
		promptType: "postgres",
		promptCode: "HV00K",
		promptCondition: "fdw_reply_handle",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 246,
		promptType: "postgres",
		promptCode: "HV00Q",
		promptCondition: "fdw_schema_not_found",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 247,
		promptType: "postgres",
		promptCode: "HV00R",
		promptCondition: "fdw_table_not_found",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 248,
		promptType: "postgres",
		promptCode: "HV00L",
		promptCondition: "fdw_unable_to_create_execution",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 249,
		promptType: "postgres",
		promptCode: "HV00M",
		promptCondition: "fdw_unable_to_create_reply",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 250,
		promptType: "postgres",
		promptCode: "HV00N",
		promptCondition: "fdw_unable_to_establish_connection",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 251,
		promptType: "postgres",
		promptCode: "P0000",
		promptCondition: "plpgsql_error",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 252,
		promptType: "postgres",
		promptCode: "P0001",
		promptCondition: "raise_exception",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 253,
		promptType: "postgres",
		promptCode: "P0002",
		promptCondition: "no_data_found",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 254,
		promptType: "postgres",
		promptCode: "P0003",
		promptCondition: "too_many_rows",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 255,
		promptType: "postgres",
		promptCode: "P0004",
		promptCondition: "assert_failure",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 256,
		promptType: "postgres",
		promptCode: "XX000",
		promptCondition: "internal_error",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 257,
		promptType: "postgres",
		promptCode: "XX001",
		promptCondition: "data_corrupted",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами",
			"Adminlarga aloqaga chiqing",
		],
	},
	{
		promptId: 258,
		promptType: "postgres",
		promptCode: "XX002",
		promptCondition: "index_corrupted",
		promptLabels: [
			"Contact administrators",
			"Связаться с администраторами?",
			"Adminlarga aloqaga chiqing",
		],
	},
];
